artifact_location: file:D:/project/Personal Project/project17_yolov8_object_detection/runs/mlflow/0
creation_time: 1765327682535
experiment_id: '0'
last_update_time: 1765327682535
lifecycle_stage: active
name: Default
